### ISSUE TITLE
Issue #04: Set up roles (admin, renter, landlord, guest)

### ISSUE THREAD

**Issue by mlee-uhm** [house-finders/house-finders#4]

**Comment by domalian** [comment]
Subroles RENTER and LANDLORD for USER role, and ADMIN subrole for ADMIN role were created. This was implemented into the signup form in which it sets USER as either LANDLORD or RENTER depending on choice. More samples were created for testing schema and local database. Total work was 2:08 hours with 20 minutes spent navigating around the files to find the certain source and type definitions. Rebased main into branch before push.

**Comment by domalian** [comment]
Issue #4: Subroles RENTER and LANDLORD for USER role, and ADMIN subrole for ADMIN role were created. This was implemented into the signup form in which it sets USER as either LANDLORD or RENTER depending on choice. More samples were created for testing schema and local database. Total work was 2:08 hours with 20 minutes included spent navigating around the files to find the certain source and type definitions. Rebased main into branch before push.

**Comment by domalian** [comment]
Issue #4: Found fix for persistent data despite running `npx prisma migrate dev` or `npx prisma db seed` by running `npx prisma migrate dev reset`.  Also added a condition in `seed.ts` to update default accounts properly. It took about an 40 minutes for finding the fix. 10 minutes for implementing the condition, and 30 minutes debugging migration issue.
